### ISSUE TITLE
Add Version to this roles

### ISSUE THREAD

**Issue by roumano** [Aplyca/ansible-role-syncs3content#1]
if possible please add version to this ansible roles.
it's recommanded in  the documenation  : http://docs.ansible.com/ansible/galaxy.html#version

it's will permit to follow version and/or stay to a specific version.

For exemple, see the warning : 
```
ansible-galaxy install -r update_roles.yml
 [WARNING]: - Aplyca.SyncS3Content (master) is already installed - use --force to change version to unspecified
- holms.fqdn (1.1) is already installed, skipping.
 [WARNING]: - geerlingguy.apache (2.0.1) is already installed - use --force to change version to 2.1.0

```

**Comment by mauricios** [comment]
@roumano yes, I'll add semantic versioning to the role.

**Comment by roumano** [comment]
hi,
any idea when it's will be done ?

**Comment by mauricios** [comment]
@roumano I completely forgot about this issue! I am so sorry. I've created the release 0.1.0 and updated Ansible Galaxy to make it available.
